import {
  pgTable,
  index,
  serial,
  text,
  varchar,
  smallint,
  integer,
  pgEnum,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const catalogType = pgEnum("catalog_type", [
  "Artikel - Restricted Use",
  "Bahan Ajar",
  "Buku - Circulation (BI Corner)",
  "Buku - Circulation (Dapat Dipinjam)",
  "Buku - Elektronik (E-Book)",
  "Buku - Elektronik (E-Book) Kindle",
  "Buku - Elektronik (E-Book) Restricted",
  "Buku - Elektronik (E-Book) Tel-U Press",
  "Buku - LAC",
  "Buku - Reference (Hanya Baca di Tempat)",
  "Buku Rekreatif - Circulation",
  "Buku Softskill - Circulation",
  "Case Studies",
  "Disertasi - Reference",
  "E-Article",
  "Institutional Content",
  "Jurnal Internasional - Reference",
  "Jurnal Nasional - Reference",
  "Jurnal Terakreditasi DIKTI - Reference",
  "Karya Ilmiah - Disertasi (S3) - Reference",
  "Karya Ilmiah - Skripsi (S1) - Reference",
  "Karya Ilmiah - TA (D3) - Reference",
  "Karya Ilmiah - Thesis (S2) - Reference",
  "Majalah - Reference",
  "Majalah Bundling",
  "Majalah Ilmiah - Reference",
  "Majalah Populer - Reference",
  "Modul Praktikum ( Electronic )",
  "Proceeding ( Electronic )",
  "e - Article Journal",
  "ePoster",
  "skripsi",
]);

export const catalog = pgTable(
  "catalog",
  {
    id: serial().primaryKey().notNull(),
    title: text().notNull(),
    catalogNumber: varchar("catalog_number", { length: 100 }),
    catalogType: catalogType("catalog_type"),
    classificationNumber: varchar("classification_number", { length: 100 }),
    subject: varchar({ length: 255 }),
    author: text(),
    editor: text(),
    publisher: text(),
    shelfNumber: varchar("shelf_number", { length: 100 }),
    libraryLocation: text("library_location"),
    publicationYear: smallint("publication_year"),
    totalCopies: integer("total_copies").default(0),
    accessLink: text("access_link"),
  },
  (table) => [
    index("catalog_publication_year_idx").using(
      "btree",
      table.publicationYear.asc().nullsLast().op("int2_ops"),
    ),
  ],
);
